# 一. ndarray
## 1.ndarray的特性
### 多维性

In [4]:
import numpy as np 

In [48]:
arr =np.array(5) # 创建一个0维数组
print (arr) 
print ('维度：',arr.ndim)  # 查看数组的维度

5
维度： 0


In [49]:
arr =np.array([1,2,3]) # 创建一个1维数组
print (arr) 
print ('维度：',arr.ndim)  # 查看数组的维度

[1 2 3]
维度： 1


In [50]:
arr =np.array([[1,2,3],[4,5,6]]) # 创建一个0维数组
print (arr) 
print ('维度：',arr.ndim)  # 查看数组的维度

[[1 2 3]
 [4 5 6]]
维度： 2


### 同质性

In [51]:
arr =np.array([1,'hello']) # 不同的数据类型会被强制转换为相同的数据类型 
print (arr) 

['1' 'hello']


In [52]:
arr =np.array([1,2.3]) # 不同的数据类型会被强制转换为相同的数据类型 
print (arr) 

[1.  2.3]


## 2.ndarray的属性 

In [ ]:
arr=np.array(1)
print (arr)
print('数组的形状：',arr.shape)
print('数组的维度：',arr.ndim)
print('元素的个数：',arr.size)
print('数据的类型：',arr.dtype)
print('元素的转置：',arr.T) # 0维数组的转置仍然是它本身

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
数据的类型： int64
元素的转置： 1


In [23]:
arr =np.array([1,2.2,3])
print (arr)
print('数组的形状：',arr.shape)
print('数组的维度：',arr.ndim)
print('元素的个数：',arr.size)
print('数据的类型：',arr.dtype)
print('元素的转置：',arr.T) # 1维数组的转置仍然是它本身

[1.  2.2 3. ]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
数据的类型： float64
元素的转置： [1.  2.2 3. ]


In [24]:
arr =np.array([[1,2,3],[4,5,6]])
print (arr)
print('数组的形状：',arr.shape)
print('数组的维度：',arr.ndim)
print('元素的个数：',arr.size)
print('数据的类型：',arr.dtype)
print('元素的转置：',arr.T) # 2维数组的转置是行列互换

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
数据的类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [96]:
# 基础的创建方法
list1=[4,5,6]
arr =np.array(list1,dtype=np.float64) # 通过列表创建一维数组,同时可以指定数组的数据类型
print (arr)
print(arr.ndim) # 查看数组的维度

[4. 5. 6.]
1


In [97]:
# copy 
arr1=np.copy(arr) # 通过np.copy()函数复制数组 元素值跟原始数组相同但内存地址不同
print(arr1)
arr1[0]=12
print(arr1)

[4. 5. 6.]
[12.  5.  6.]


In [98]:
# 预定义形状
# 全0数组 全1数组 未初始化 固定值
#全0数组
arr=np.zeros((2,3)) # 创建2行3列的全0数组
print(arr)
print(arr.dtype) # 默认数据类型为float64

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [99]:
arr=np.zeros(2) # 创建1维全0数组
print(arr)

[0. 0.]


In [100]:
# 全1数组
arr=np.ones((2,3)) # 创建2行3列的全1数组
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [101]:
# 未初始化数组
arr=np.empty((2,3)) # 创建2行3列的未初始化数组
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [102]:
# 固定值数组
arr=np.full((3,4),2) # 创建3行4列的元素值全部为2的数组
print(arr)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [111]:
arr1=np.zeros_like(arr) # 创建一个形状和arr相同的全0数组
print(arr1)
arr1=np.empty_like(arr) # 创建一个形状和arr相同的未初始化数组
print(arr1)
arr1=np.full_like(arr,999) # 创建一个形状和arr相同的元素值全部为23的数组
print(arr1)
arr1=np.ones_like(arr) # 创建一个形状和arr相同的全1数组
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[999 999 999 999]
 [999 999 999 999]
 [999 999 999 999]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [112]:
# 等差数列
arr=np.arange(1,10,3) # 创建一个等差数列数组 起始值1 终止值10 步长3
print(arr)

[1 4 7]


In [113]:
# 等间隔数列
arr=np.linspace(1,10,5) # 创建一个等间隔数列数组 起始值1 终止值10 元素个数5
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [120]:
arr=np.linspace(0,100,5,dtype=int) # 创建一个等间隔数列数组 起始值0 终止值101 元素个数5 数据类型int32
print(arr)
arr=np.arange(0,101,25,dtype=int) # 创建一个等差数列数组 起始值0 终止值101 步长25 数据类型int32
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [ ]:
# 对数间隔数列
arr=np.logspace(0,4,2,base=2) # 创建一个对数间隔数列数组 起始值2的0次方 终止值2的4次方 元素个数2,不指定base默认以10为底
print(arr)

[ 1. 16.]


In [127]:
# 特殊矩阵
# 单位矩阵 主对角线为1 其余元素为0的方阵
arr=np.eye(4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [130]:
# 对角矩阵 主对角线上有指定值 其余元素为0
arr=np.diag([1,2,3,4,5,6])
print(arr)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [ ]:
# 随机数组的创建
arr=np.random.rand(2,3) # 创建2行3列的0到1之间均匀分布的随机数组
print(arr)

[[0.1630532  0.80567519 0.08046719]
 [0.80681081 0.61058403 0.29089302]]


In [152]:
#生成指定范围区间的随机浮点数
arr=np.random.uniform(2,4,(3,4))
print(arr)

[[2.97115863 3.68566292 3.09043424 3.8061833 ]
 [3.27661655 3.53587238 3.08234524 3.49349258]
 [2.54172006 3.66769187 2.92142816 2.07691085]]


In [153]:
# 生成指定范围区间的随机整数
arr=np.random.randint(5,20,(3,4)) # 生成3行4列 5到20之间的随机整数数组
print(arr)

[[19 15 10 15]
 [ 5  7 16  9]
 [14 18 16  6]]


In [159]:
# 生成随机正态分布数组
arr=np.random.randn(2,3)
print(arr)

[[ 1.08026514 -0.45917481  0.84563394]
 [-1.55834621  1.19906523 -2.3907215 ]]


In [171]:
# 设置随机种子
np.random.seed(20) # 设置随机种子为20
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


In [172]:
print('才是你的吗')

才是你的吗
