# 一. ndarray
## 1.ndarray的特性
### 多维性

In [1]:
import numpy as np

In [2]:
arr =np.array(5) # 创建一个0维数组
print(arr) 
print ('维度：',arr.ndim)  # 查看数组的维度

5
维度： 0


In [3]:
arr =np.array([1,2,3]) # 创建一个1维数组
print (arr) 
print ('维度：',arr.ndim)  # 查看数组的维度

[1 2 3]
维度： 1


In [4]:
arr =np.array([[1,2,3],[4,5,6]]) # 创建一个0维数组
print (arr) 
print ('维度：',arr.ndim)  # 查看数组的维度

[[1 2 3]
 [4 5 6]]
维度： 2


### 同质性

In [5]:
arr =np.array([1,'hello']) # 不同的数据类型会被强制转换为相同的数据类型 
print (arr) 

['1' 'hello']


In [6]:
arr =np.array([1,2.3]) # 不同的数据类型会被强制转换为相同的数据类型 
print (arr) 

[1.  2.3]


## 2.ndarray的属性 

In [7]:
arr=np.array(1)
print (arr)
print('数组的形状：',arr.shape)
print('数组的维度：',arr.ndim)
print('元素的个数：',arr.size)
print('数据的类型：',arr.dtype)
print('元素的转置：',arr.T) # 0维数组的转置仍然是它本身

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
数据的类型： int64
元素的转置： 1


In [8]:
arr =np.array([1,2.2,3])
print (arr)
print('数组的形状：',arr.shape)
print('数组的维度：',arr.ndim)
print('元素的个数：',arr.size)
print('数据的类型：',arr.dtype)
print('元素的转置：',arr.T) # 1维数组的转置仍然是它本身

[1.  2.2 3. ]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
数据的类型： float64
元素的转置： [1.  2.2 3. ]


In [9]:
arr =np.array([[1,2,3],[4,5,6]])
print (arr)
print('数组的形状：',arr.shape)
print('数组的维度：',arr.ndim)
print('元素的个数：',arr.size)
print('数据的类型：',arr.dtype)
print('元素的转置：',arr.T) # 2维数组的转置是行列互换

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
数据的类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [10]:
# 基础的创建方法
list1=[4,5,6]
arr =np.array(list1,dtype=np.float64) # 通过列表创建一维数组,同时可以指定数组的数据类型
print (arr)
print(arr.ndim) # 查看数组的维度

[4. 5. 6.]
1


In [11]:
# copy 
arr1=np.copy(arr) # 通过np.copy()函数复制数组 元素值跟原始数组相同但内存地址不同
print(arr1)
arr1[0]=12
print(arr1)

[4. 5. 6.]
[12.  5.  6.]


In [12]:
# 预定义形状
# 全0数组 全1数组 未初始化 固定值
#全0数组
arr=np.zeros((2,3)) # 创建2行3列的全0数组
print(arr)
print(arr.dtype) # 默认数据类型为float64

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [13]:
arr=np.zeros(2) # 创建1维全0数组
print(arr)

[0. 0.]


In [14]:
# 全1数组
arr=np.ones((2,3)) # 创建2行3列的全1数组
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# 未初始化数组
arr=np.empty((2,3)) # 创建2行3列的未初始化数组
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# 固定值数组
arr=np.full((3,4),2) # 创建3行4列的元素值全部为2的数组
print(arr)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [17]:
arr1=np.zeros_like(arr) # 创建一个形状和arr相同的全0数组
print(arr1)
arr1=np.empty_like(arr) # 创建一个形状和arr相同的未初始化数组
print(arr1)
arr1=np.full_like(arr,999) # 创建一个形状和arr相同的元素值全部为23的数组
print(arr1)
arr1=np.ones_like(arr) # 创建一个形状和arr相同的全1数组
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[      2551347836456                  64                   0
                    0]
 [  32651548270002176 7016946209250228534 7089000297789743920
  7363773958140211301]
 [4123388727243858529 3616451395700470836 3690756194004329264
  7147272211615987764]]
[[999 999 999 999]
 [999 999 999 999]
 [999 999 999 999]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
# 等差数列
arr=np.arange(1,10,3) # 创建一个等差数列数组 起始值1 终止值10 步长3
print(arr)

[1 4 7]


In [19]:
# 等间隔数列
arr=np.linspace(1,10,5) # 创建一个等间隔数列数组 起始值1 终止值10 元素个数5
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [20]:
arr=np.linspace(0,100,5,dtype=int) # 创建一个等间隔数列数组 起始值0 终止值101 元素个数5 数据类型int32
print(arr)
arr=np.arange(0,101,25,dtype=int) # 创建一个等差数列数组 起始值0 终止值101 步长25 数据类型int32
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [21]:
# 对数间隔数列
arr=np.logspace(0,4,2,base=2) # 创建一个对数间隔数列数组 起始值2的0次方 终止值2的4次方 元素个数2,不指定base默认以10为底
print(arr)

[ 1. 16.]


In [22]:
# 特殊矩阵
# 单位矩阵 主对角线为1 其余元素为0的方阵
arr=np.eye(4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [23]:
# 对角矩阵 主对角线上有指定值 其余元素为0
arr=np.diag([1,2,3,4,5,6])
print(arr)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [24]:
# 随机数组的创建
arr=np.random.rand(2,3) # 创建2行3列的0到1之间均匀分布的随机数组
print(arr)

[[0.19796333 0.38336804 0.76378464]
 [0.62362631 0.59635705 0.25940658]]


In [25]:
#生成指定范围区间的随机浮点数
arr=np.random.uniform(2,4,(3,4))
print(arr)

[[2.53082865 3.26889082 2.40617493 3.95503925]
 [2.54301832 3.1166952  3.33801206 2.72828713]
 [3.1185458  2.60537876 3.55432128 3.65113333]]


In [26]:
# 生成指定范围区间的随机整数
arr=np.random.randint(5,20,(3,4)) # 生成3行4列 5到20之间的随机整数数组
print(arr)

[[14 10 13 15]
 [ 7  6 14  7]
 [16 14  6 10]]


In [27]:
# 生成随机正态分布数组
arr=np.random.randn(2,3)
print(arr)

[[-0.20910228  0.28466729  0.0670763 ]
 [ 2.23425758  0.26073126  0.0766969 ]]


In [28]:
# 设置随机种子
np.random.seed(20) # 设置随机种子为20
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


In [29]:
print('才是你的吗')

才是你的吗


# 4.ndarray的数据类型
## 布尔类型
## 整数类型
## 浮点数类型
## 复数 complex

In [30]:
arr=np.array([1,0,8000,0],dtype=int)
print(arr)

[   1    0 8000    0]


# 5.索引与切片

In [31]:
# 一维数组的索引与切片
arr=np.random.randint(1,100,20)



In [32]:
print(arr)

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]


In [33]:
print(arr[10]) # 获取指定位置的元素
print(arr[:]) # 获取整个数组
print(arr[2:5]) # 获取从索引2到索引5（不包含5）的元素
print(arr[slice(2,15,3)]) # 获取从索引2到索引15（不包含15）之间 步长为3的元素
print(arr[(arr>10)&(arr<70)]) # bool索引



26
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[17  7 76  4 62]
[17 63 17 27 14 59 26 62 58 33]


In [34]:
# 二维数组的索引与切片
arr=np.random.randint(1,100,(4,5))


In [35]:
print(arr)

[[11  7 76 19  4]
 [78 18 44 17 19]
 [80 91 60 72 76]
 [30 46  7 64 79]]


In [36]:
print(arr[1,1]) # 索引
print(arr[:,:]) # 获取整个数组
print(arr[1,:]) # 获取第2行的所有元素
print(arr[:,1]) # 获取第2列的所有元素
print(arr[1,1:4]) # 获取第2行中索引1到索引4（不包含4）的元素
print(arr[0:4,1]) # 获取第2列中索引0到索引4（不包含4）的元素
print(arr[2][arr[2]>20]) # 获取第3行中大于20的元素
print(arr[:,2][arr[:,2]>20]) # 获取第3列中大于20的元素

18
[[11  7 76 19  4]
 [78 18 44 17 19]
 [80 91 60 72 76]
 [30 46  7 64 79]]
[78 18 44 17 19]
[ 7 18 91 46]
[18 44 17]
[ 7 18 91 46]
[80 91 60 72 76]
[76 44 60]


# 6.ndarray的运算

In [37]:
# 算术运算
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
print(a+b) # 数组对应元素相加
print(a-b) # 数组对应元素相减
print(a*b) # 数组对应元素相乘
print(a/b) # 数组对应元素相除

c=[1,2,3]
d=[4,5,6]
print(c+d) # 列表相加是列表拼接 

[[5 7 9]]
[[-3 -3 -3]]
[[ 4 10 18]]
[[0.25 0.4  0.5 ]]
[1, 2, 3, 4, 5, 6]


In [38]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+b) # 数组对应元素相加
print(a-b) # 数组对应元素相减
print(a*b) # 数组对应元素相乘
print(a/b) # 数组对应元素相除

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
# 数组与标量运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3) # 数组的每个元素都加3
print(a*3) # 数组的每个元素都乘3


[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [40]:
# 广播机制
# 同一维度下 形状不同的数组进行算术运算时 会自动将形状较小的数组沿着维度进行拉伸 使得两个数组的形状相同后 再进行对应元素的运算 这种机制称为广播机制
a=np.array([1,2,3])
b=np.array([[1],[2],[3]])
print(a.shape) 
print(b.shape)
print(a+b) # 广播机制下数组相加 拉伸a的形状为(3,) b的形状为(3,1) 通过广播机制后 a的形状变为(1,3) 再拉伸为(3,3) b的形状变为(3,1) 再拉伸为(3,3) 最终进行对应元素相加
# 以下同理
print(a-b) 
print(a*b)
print(a/b)


(3,)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1.         2.         3.        ]
 [0.5        1.         1.5       ]
 [0.33333333 0.66666667 1.        ]]


In [41]:
# 矩阵运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a*b) # 数组对应元素相乘
print(a@b) # 矩阵乘法

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# 7.numpy中的常用函数
## 1.基本数学函数

In [42]:
# 计算平方根
print(np.sqrt(9)) #永远返回算术平方根，负数会给出nan并警告  sqrt
print(np.sqrt([1,4,9])) # 计算数组中每个元素的平方根
arr=np.array([25,16,81])
print(np.sqrt(arr)) # 计算数组中每个元素的平方根

3.0
[1. 2. 3.]
[5. 4. 9.]


In [43]:
# 计算指数 e^x
print(np.exp(0)) # e的0次方=1    exp

1.0


In [44]:
# 计算自然对数 lnX
print(np.log(2.718281828459045)) # 计算e的自然对数，结果接近1   log

1.0


In [45]:
# 计算三角函数
print(np.sin(1))    # sin 正弦值
print(np.cos(0))    # cos 余弦值

0.8414709848078965
1.0


In [46]:
# 计算绝对值
arr=np.array([1,23,-4,-4])
print(np.abs(arr))  # abs

[ 1 23  4  4]


In [47]:
# 计算a的b次方
print(np.power(arr,3))  #power

[    1 12167   -64   -64]


In [48]:
# 四舍五入
print(np.round([1.2,2.5,3.5,8.5])) # 默认使用银行家舍入法即：遇5看前一位，奇进偶不进    # round

[1. 2. 4. 8.]


In [49]:
# 向上取整 向下取整
a=np.array([1.2,2.5,3.5,8.5])
print(np.ceil(a)) # 向上取整    # ceil
print(np.floor(a)) # 向下取整   #floor

[2. 3. 4. 9.]
[1. 2. 3. 8.]


In [50]:
# 检测缺失值
np.isnan([1,np.nan,2,3])    # isnan

array([False,  True, False, False])

## 2.统计函数

### 求和、平均值、标准差、方差等

### 查找最大值，最小值及其索引

### 计算分位数、累积和、累积差

In [51]:
arr=np.random.randint(1,100,8)
print(arr)
print(np.sum(arr))  # 计算数组元素的和    sum

[25 19 94 34 79 43 95  4]
393


In [52]:
# 计算平均值
print(np.mean(arr)) # mean

49.125


In [53]:
# 计算中位数
print(np.median([1,2,6,4])) #   排序之后    median
print(np.median([1,2,3]))

3.0
2.0


In [54]:
# 计算标准差、方差
print(np.std([1,2,4])) # 标准差     std
print(np.var([1,2,3])) # 方差 离散程度的度量    var

1.247219128924647
0.6666666666666666


In [55]:
# 最值计算
print(arr)
print(np.max(arr),'最大值的索引：',np.argmax(arr)) #  最大值及其索引    max
print(np.min(arr),'最小值的索引：',np.argmin(arr)) #  最小值及其索引    min

[25 19 94 34 79 43 95  4]
95 最大值的索引： 6
4 最小值的索引： 7


In [56]:
# 分位数
np.random.seed(0) # 设置随机种子
arr=np.random.randint(0,100,4)
print(arr)
print(np.median(arr)) # 中位数  median
print(np.percentile(arr,25)) # percentile(q)中的q表示百分比     percentile


[44 47 64 67]
55.5
46.25


In [57]:
# 累积和、累积积
arr=np.array([1,2,3])
print(np.cumsum(arr))   # 累积和    cumsum
print(np.cumprod(arr))  # 累积积    cumprod

[1 3 6]
[1 2 6]


## 比较函数

### 1.大于 小于 等于
### 2.逻辑与、或、非
### 3.检查数组中是否至少有一个为True，是否所有的都为true，自定义条件

In [58]:
# 1
# 将元素与指定值进行比较，结果只能是True或False
print(np.greater([3,4,5,6,7],4)) # 判断是否大于4    greater
print(np.less([3,4,5,6,7],4)) # 判断是否小于4   less
print(np.equal([3,4,5,6,7],4)) # 判断是否等于4  equal
print(np.not_equal([3,4,4,5,6,7],4)) # 判断是否不等于4  not_equal
print(np.equal([3,4,5],[4,4,4])) # 判断数组里的对应元素是否相等。逐元素比较，形状必须相同或者能广播 
# print(np.equal([3,4,5],[2,2])) 形状不匹配报错也不能广播

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[ True False False  True  True  True]
[False  True False]


In [59]:
# 逻辑与或非
print(np.logical_and([1,1],[1,0]))  # 逻辑与 类比串联电路   logical_and
print(np.logical_or([1,0],[0,0]))   # 逻辑或 类比并联电路   logical_or
print(np.logical_not([1,0,1,1,0]))  # 逻辑非 取反   logical_not
print(~np.array([1,0,1,1,0],dtype=bool))  # 等价于上一段代码，但是要指定数据类型为bool！！！

[ True False]
[ True False]
[False  True False False  True]
[False  True False False  True]


In [60]:
# 检查元素是否至少有一个元素为True
print(np.any([0,0,0,0,1])) # any
# 检查元素是否全部为True
print(np.all([0,0,0,0,1])) # all

True
False


In [61]:
# 自定义条件
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.where(arr%2==0,arr,0)) # （条件，A，B）满足条件则取A的值，否则取B的值  np.where

[0 2 0 4 0 6 0 8 0]


In [62]:
np.random.seed(0) # 设置随机种子 固定随机数序列
dick=np.random.randint(0,100,20)
print(dick)
print(np.where(dick>60,'牛逼','傻逼'))

[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
['傻逼' '傻逼' '牛逼' '牛逼' '牛逼' '傻逼' '牛逼' '傻逼' '傻逼' '牛逼' '牛逼' '牛逼' '牛逼' '傻逼'
 '傻逼' '牛逼' '傻逼' '牛逼' '傻逼' '牛逼']


In [63]:
# 嵌套使用np.where
np.random.seed(0)
dick=np.random.randint(0,100,20)
print(dick)
print(np.where(
    dick<50,'傻逼',np.where(
        dick<70,'中逼','牛逼'
    )
))
#   print(np.select([dick>70,(dick>=50)&(dick<=70),dick<50],['牛逼','中逼','傻逼'],default='none')) 便于维护    select

[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
['傻逼' '傻逼' '中逼' '中逼' '中逼' '傻逼' '牛逼' '傻逼' '傻逼' '牛逼' '牛逼' '牛逼' '牛逼' '傻逼'
 '中逼' '中逼' '傻逼' '牛逼' '傻逼' '牛逼']


In [64]:
# 排序函数
np.random.seed(0) # 固定
arr=np.random.randint(0,100,20)
print(arr)
# arr.sort()
# print(arr)  # 这种方法会改变原始列表，该方法直接对原始列表进行操作，返回值为none
print(np.sort(arr)) # 这种方法不会改变原始列表 将排序后的元素放进一个新列表里，不改变原列表     sort
print(np.argsort(arr)) # 获取排序后对应值原来的索引     argsort
print(arr)  # 原列表没有发生改变

[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
[ 9 12 21 36 39 44 46 47 58 64 65 67 67 70 83 87 87 88 88 88]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]


In [65]:
# 去重函数
print(np.unique(arr)) # 去重并自动排序  unique

[ 9 12 21 36 39 44 46 47 58 64 65 67 70 83 87 88]


In [66]:
# 数组的拼接
j=np.array([1,2,3])
k=np.array([4,5,6])
print(j+k)  
print(np.concatenate((j,k)))    # concatenate

[5 7 9]
[1 2 3 4 5 6]


In [67]:
# 数组的分割
print(np.split(arr,[6,12,18]))  # 需要能够等分 如果不能够等分，需要手动分割     split

[array([44, 47, 64, 67, 67,  9], dtype=int32), array([83, 21, 36, 87, 70, 88], dtype=int32), array([88, 12, 58, 65, 39, 87], dtype=int32), array([46, 88], dtype=int32)]


In [68]:
# 调整数组形状
print(np.reshape(arr,[4,5]))   # reshape

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]]


#  第二章 NumPy 科学计算综合练习

### eg1：温度数据分析
### 某城市一周的最高气温为[28,30,29,31,32,30,29]
###     计算平均气温、最高气温和最低气温
###     找出气温超过30的天数

In [69]:
import numpy as np
temps=np.array([28,30,29,31,32,30,29])
print(temps)
print('平均气温',np.mean(temps,dtype=int))
print('最高气温',np.max(temps))
print('最低气温',np.min(temps))
print('气温超过30的天数：',len(temps[temps>30]))
# print('气温超过30的天数：',np.cumsum(np.where(temps>30,1,0))[-1])
# print('气温超过30的天数：',np.count_nonzero(temps>30))

[28 30 29 31 32 30 29]
平均气温 29
最高气温 32
最低气温 28
气温超过30的天数： 2


### eg2:学生成绩统计
### 某班级5名学生的数学成绩是[85,90,78,92,88]
### 计算成绩的平均分、中位数和标准差
### 将成绩转化为百分制（假设满分为10）

In [70]:
import numpy as np
score=np.array([85,90,78,92,88])
print('平均分：',np.mean(score))
print('中位数：',np.median(score))
print('标准差：',np.std(score))
print(score/10)

平均分： 86.6
中位数： 88.0
标准差： 4.882622246293481
[8.5 9.  7.8 9.2 8.8]


### eg3: 矩阵运算
### 给定矩阵 A=[[1,2],[3,4]] 和B=[[5,6],[7,8]]
### 计算A+B和A*B(逐元素乘法)
### 计算A和B的矩阵乘法（点积）

In [71]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print('A+B:',A+B)
print('A*B:',A*B)
print(A@B)
# print(np.dot(A,B))

A+B: [[ 6  8]
 [10 12]]
A*B: [[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


### eg4: 随机数据生成
### 生成一个（3，4）的随机整数数组，范围[0，10）
### 计算每列的最大值和每行的最小值
### 将数组中的所有奇数替换为-1

In [72]:
np.random.seed(0)
arr=np.random.randint(0,10,size=(3,4))
print(arr)
print('每列最大值分别是：',np.max(arr,axis=0)) 
print('每行最小值分别是：',np.min(arr,axis=1)) 
print('替换奇数为-1:\n',np.where(arr%2==1,-1,arr))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列最大值分别是： [7 9 7 6]
每行最小值分别是： [0 3 2]
替换奇数为-1:
 [[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


### eg5:数组变形
### 创建一个1-12的一维数组，并转变为（3，4）的二位数组
### 计算每行的和与每列的平均值
### 将数组展平为一维数组

In [73]:
arr=np.arange(1,13)
print(arr)
arr1=np.reshape(arr,(3,4))
print(arr1)
print('每行的和分别为:',np.sum(arr1,axis=1))
print('每列的平均值分别为：',np.mean(arr1,axis=0))
print('展开为一维数组：',np.reshape(arr1,(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和分别为: [10 26 42]
每列的平均值分别为： [5. 6. 7. 8.]
展开为一维数组： [ 1  2  3  4  5  6  7  8  9 10 11 12]


### eg6:布尔索引
### 生成一个（5，5）的随机数组，范围[0，20）
### 找出数组中大于10的元素
### 将所有大于10的元素替换为0

In [74]:
np.random.seed(0)
arr=np.random.randint(0,20,(5,5))
print(arr)
print('数组中大于10的数：',arr[arr>10])
arr[arr>10]=0
print('替换大于10的数为0\n',arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
数组中大于10的数： [12 15 19 18 12 14 17 13 19 16 19]
替换大于10的数为0
 [[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


### eg7:统计函数应用
### 某公司6个月的销售额（万元）为[120，135，110，125，130，140]
### 计算销售额的总和、均值和方差
### 找出销售额最高的月份和最低的月份

In [75]:
arr=np.array([120,135,110,125,130,140])
print(arr)
print('总和:',np.sum(arr))
print('均值：',np.mean(arr))
print('方差:',np.var(arr))
print('最高的月份：',np.argmax(arr)+1)
print('最低的月份：',np.argmin(arr)+1)

[120 135 110 125 130 140]
总和: 760
均值： 126.66666666666667
方差: 97.22222222222223
最高的月份： 6
最低的月份： 3


### eg8: 数组拼接
### 给定 A=[1,2,3]和B=[4,5,6]
### 将A和B水平拼接为一个新数组
### 将A和B垂直拼接为一个新数组

In [76]:
A=np.array([1,2,3])
B=np.array([4,5,6])
C=np.concatenate([A,B])
print('水平拼接：',C)
print('垂直拼接:\n',np.reshape(C,(2,3)))

水平拼接： [1 2 3 4 5 6]
垂直拼接:
 [[1 2 3]
 [4 5 6]]


### eg9: 唯一值和排序
### 给定数组[2,1,2,3,1,4,3]
### 找出数组中的唯一值并排序
### 计算每一个唯一值出现的次数

In [77]:
arr=np.array([2,1,2,3,1,4,3])
u_arr,counts=np.unique(arr,return_counts=True)
print(u_arr)
print(counts)

[1 2 3 4]
[2 2 2 1]


### eg10: 综合应用
### 某商店5天的销售额（万元）和成本（万元）如下
### 销售额[20,25,22,30,28]
### 成本[15,18,16,22,20]
### 计算每天的利润
### 计算利润的平均值和标准差
### 找出利润最高的天数

In [78]:
money=np.array([20,25,22,30,28])
base=np.array([15,18,16,22,20])
youshui=money-base
print('每天的利润分别是(万元)：',youshui)
print('平均利润(万元)：',np.mean(youshui),'利润的标准差是：',np.std(youshui))
print('利润最高的天数：',len(youshui[youshui==np.max(youshui)]))

每天的利润分别是(万元)： [5 7 6 8 8]
平均利润(万元)： 6.8 利润的标准差是： 1.16619037896906
利润最高的天数： 2
